### ISSUE TITLE
Free-form rectangle area selection

### ISSUE THREAD

**Issue by keunes** [MATHEMA-GmbH/privacyblur#74]
Hello

I just found your app through FDroid. Great concept, but I find the UI a bit hard to use.

One point specifically that would help a lot is freeform rectangle selection. Right now, pixelating an email address requires many small rectangles to be placed. It'd be much easier if I could just drag and select.

Thanks for your contribution to the open source ecosystem!

**Comment by tkuenneth** [comment]
Hello. Thanks a lot for giving the app a try. I am pleased to say that I, too, think the app would benefit from a freeform rectangle selection. It may take some time, but we will add one. I keep this issue open until the new version is online.

**Comment by tkuenneth** [comment]
We implemented this. I therefore close the issue. Thanks for reporting.
